### ISSUE TITLE
Blockchain Discord Group 

### ISSUE THREAD

**Issue by Vivekbhusal** [developers-nepal/groups#8]
Says invitation invalid or expired. How can I join?

https://discordapp.com/invite/QcxkQZA
<img width="858" alt="screen shot 2018-03-20 at 11 08 37 am" src="https://user-images.githubusercontent.com/1974260/37628782-29bfbc6a-2c2f-11e8-9ef4-88e0d6f2f491.png">

**Comment by nepalbitcoin** [comment]
@Vivekbhusal 
https://discordapp.com/invite/ewJ4Mzm
